### ISSUE TITLE
Help Consume from Postman

### ISSUE THREAD

**Issue by DGoRdriguez** [kaarthikin/asp_net_core_custom_authorize_attribute#1]
Hello Karthinkin, help me please, how can i do the request for a metod with the atribute A1AuthorizePermission from Postmand? Thank you

**Comment by kaarthikin** [comment]
Hi DGoRdriguez,

Am not clear with your question, could you please elaborate or give an example.

**Comment by DGoRdriguez** [comment]
Thanks Karthinkin,
I have method but in postman response 404.
[AuthorizePermission(Permissions = "CanRead")]
        public async Task<RetornoTransaccion> ValidarRecaptcha(string captcha)
        {
            var retorno = new RetornoTransaccion();
            if (!await _captchaValidator.IsCaptchaPassedAsync(captcha))
            {
                retorno.TransaccionExitosa = false;
                retorno.MensajeRetorno = "Validación de Recaptcha invalido.";
            }

            return retorno;
        }

![image](https://user-images.githubusercontent.com/2366957/92998086-7a002100-f4dd-11ea-9475-6eb528925591.png)

**Comment by kaarthikin** [comment]
Hi DGoRdriguez,

Could you please add the Http action verbs attribute [HttpGet] or [HttpPost] and try again.
